-- ScoutLens seed data: positions (4 rows)
-- Generated by etl/export-seed.js - do not edit by hand.

USE scoutlens;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `positions`;

INSERT INTO `positions` (`position_id`, `code`, `name`, `sort_order`) VALUES
  (1,'GK','Goalkeeper',1),
  (2,'DF','Defender',2),
  (3,'MF','Midfielder',3),
  (4,'FW','Forward',4);

SET FOREIGN_KEY_CHECKS = 1;
