-- ScoutLens seed data: seasons (6 rows)
-- Generated by etl/export-seed.js - do not edit by hand.

USE scoutlens;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `seasons`;

INSERT INTO `seasons` (`season_id`, `label`, `start_year`, `end_year`) VALUES
  (1,'2020-2021',2020,2021),
  (2,'2021-2022',2021,2022),
  (3,'2022-2023',2022,2023),
  (4,'2023-2024',2023,2024),
  (5,'2024-2025',2024,2025),
  (6,'2025-2026',2025,2026);

SET FOREIGN_KEY_CHECKS = 1;
