-- ScoutLens seed data: leagues (5 rows)
-- Generated by etl/export-seed.js - do not edit by hand.

USE scoutlens;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `leagues`;

INSERT INTO `leagues` (`league_id`, `fbref_code`, `name`, `country_code`, `country_name`) VALUES
  (1,'de Bundesliga','Bundesliga','GER','Germany'),
  (2,'fr Ligue 1','Ligue 1','FRA','France'),
  (3,'eng Premier League','Premier League','ENG','England'),
  (4,'it Serie A','Serie A','ITA','Italy'),
  (5,'es La Liga','La Liga','ESP','Spain');

SET FOREIGN_KEY_CHECKS = 1;
