-- ScoutLens seed data: fantasy_rulesets (2 rows)
-- Generated by etl/export-seed.js - do not edit by hand.

USE scoutlens;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `fantasy_rulesets`;

INSERT INTO `fantasy_rulesets` (`ruleset_id`, `name`, `description`, `is_active`, `created_at`) VALUES
  (1,'Classic','Fantasy Premier League style scoring adapted to season totals.',1,'2026-09-10 10:35:55'),
  (2,'Attack Heavy','Rewards goal involvement far more than defensive output.',0,'2026-09-10 10:35:55');

SET FOREIGN_KEY_CHECKS = 1;
