-- ScoutLens seed data: fantasy_scoring_rules (26 rows)
-- Generated by etl/export-seed.js - do not edit by hand.

USE scoutlens;
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `fantasy_scoring_rules`;

INSERT INTO `fantasy_scoring_rules` (`rule_id`, `ruleset_id`, `stat_key`, `position_id`, `points`, `unit`, `category`, `description`) VALUES
  (1,1,'matches_played',NULL,'1.00',1,'appearance','1 pt per appearance'),
  (2,1,'starts',NULL,'1.00',1,'appearance','1 extra pt per start (60+ min proxy)'),
  (3,1,'goals',1,'6.00',1,'attack','6 pts per goal (GK)'),
  (4,1,'goals',2,'6.00',1,'attack','6 pts per goal (DF)'),
  (5,1,'goals',3,'5.00',1,'attack','5 pts per goal (MF)'),
  (6,1,'goals',4,'4.00',1,'attack','4 pts per goal (FW)'),
  (7,1,'assists',NULL,'3.00',1,'attack','3 pts per assist'),
  (8,1,'pens_won',NULL,'1.00',1,'attack','1 pt per penalty won'),
  (9,1,'clean_sheets',1,'4.00',1,'defence','4 pts per clean sheet (GK)'),
  (10,1,'clean_sheets',2,'4.00',1,'defence','4 pts per clean sheet (DF)'),
  (11,1,'clean_sheets',3,'1.00',1,'defence','1 pt per clean sheet (MF)'),
  (12,1,'saves',1,'1.00',3,'defence','1 pt per 3 saves'),
  (13,1,'pens_saved',1,'5.00',1,'defence','5 pts per penalty saved'),
  (14,1,'goals_against',1,'-1.00',2,'defence','-1 pt per 2 goals conceded'),
  (15,1,'cards_yellow',NULL,'-1.00',1,'discipline','-1 pt per yellow card'),
  (16,1,'cards_red',NULL,'-3.00',1,'discipline','-3 pts per red card'),
  (17,1,'own_goals',NULL,'-2.00',1,'discipline','-2 pts per own goal'),
  (18,1,'pens_missed',NULL,'-2.00',1,'discipline','-2 pts per penalty missed'),
  (19,2,'matches_played',NULL,'0.50',1,'appearance','0.5 pt per appearance'),
  (20,2,'goals',NULL,'8.00',1,'attack','8 pts per goal, any position'),
  (21,2,'assists',NULL,'5.00',1,'attack','5 pts per assist'),
  (22,2,'pens_won',NULL,'2.00',1,'attack','2 pts per penalty won'),
  (23,2,'clean_sheets',1,'2.00',1,'defence','2 pts per clean sheet (GK)'),
  (24,2,'saves',1,'1.00',4,'defence','1 pt per 4 saves'),
  (25,2,'cards_red',NULL,'-2.00',1,'discipline','-2 pts per red card'),
  (26,2,'own_goals',NULL,'-2.00',1,'discipline','-2 pts per own goal');

SET FOREIGN_KEY_CHECKS = 1;
