// ---------------------------------------------------------------------
// ScoutLens - dumps the loaded database to plain .sql seed files.
//
//   node etl/export-seed.js
//
// This produces db/seed/*.sql so the database can be rebuilt from SQL
// alone - no Node, no CSV, no pandas - which is what a marker or a
// teammate with only MySQL Workbench needs:
//
//   mysql -u root -p < db/schema/01_schema.sql   (and 02, 03)
//   mysql -u root -p scoutlens < db/seed/*.sql
//   mysql -u root -p < db/logic/*.sql
// ---------------------------------------------------------------------

import fs from 'node:fs';
import path from 'node:path';
import mysql from 'mysql2/promise';
import { dbConfig, ROOT } from './config.js';

// Order matters: parents before children, so the dump replays cleanly.
const TABLES = [
  'positions', 'seasons', 'leagues', 'nations', 'teams', 'players',
  'player_seasons', 'player_season_positions',
  'stats_standard', 'stats_shooting', 'stats_keeper',
  'stats_playing_time', 'stats_misc',
  'fantasy_rulesets', 'fantasy_scoring_rules',
];

const ROWS_PER_INSERT = 500;
const OUT_DIR = path.join(ROOT, 'db', 'seed');

/** Renders one value as a SQL literal. */
function literal(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (value instanceof Date) return `'${value.toISOString().slice(0, 19).replace('T', ' ')}'`;
  if (Buffer.isBuffer(value)) value = value.toString('utf8');
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "''").replace(/\r?\n/g, '\\n')}'`;
}

const conn = await mysql.createConnection(dbConfig);
fs.mkdirSync(OUT_DIR, { recursive: true });

let index = 1;
for (const table of TABLES) {
  const [columns] = await conn.query(
    `SELECT COLUMN_NAME AS name, EXTRA AS extra
       FROM information_schema.COLUMNS
      WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?
      ORDER BY ORDINAL_POSITION`, [dbConfig.database, table]);

  // Generated columns (players.born_key) cannot appear in an INSERT.
  const names = columns.filter((c) => !/GENERATED/i.test(c.extra)).map((c) => c.name);
  const [rows] = await conn.query(`SELECT ${names.map((n) => `\`${n}\``).join(', ')} FROM \`${table}\``);

  const file = path.join(OUT_DIR, `${String(index).padStart(2, '0')}_${table}.sql`);
  const out = fs.createWriteStream(file, 'utf8');
  out.write(`-- ScoutLens seed data: ${table} (${rows.length.toLocaleString()} rows)\n`);
  out.write(`-- Generated by etl/export-seed.js - do not edit by hand.\n\n`);
  out.write(`USE scoutlens;\n`);
  out.write(`SET FOREIGN_KEY_CHECKS = 0;\n`);
  out.write(`DELETE FROM \`${table}\`;\n\n`);

  const colList = names.map((n) => `\`${n}\``).join(', ');
  for (let i = 0; i < rows.length; i += ROWS_PER_INSERT) {
    const chunk = rows.slice(i, i + ROWS_PER_INSERT);
    const values = chunk
      .map((r) => `(${names.map((n) => literal(r[n])).join(',')})`)
      .join(',\n  ');
    out.write(`INSERT INTO \`${table}\` (${colList}) VALUES\n  ${values};\n`);
  }

  out.write(`\nSET FOREIGN_KEY_CHECKS = 1;\n`);
  await new Promise((resolve) => out.end(resolve));
  const kb = (fs.statSync(file).size / 1024).toFixed(0);
  console.log(`  ${path.basename(file).padEnd(34)} ${String(rows.length).padStart(7)} rows  ${kb} KB`);
  index++;
}

await conn.end();
console.log(`\nWrote ${TABLES.length} seed files to db/seed/.`);
